name: recipes_app

version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_hooks: ^0.18.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
